version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --insecure  # using --insecure to acknowledge that Django shouldn't be used to serve files in production
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
