version: "3.7"

services:
  postgresql-service:
    container_name: postgresql-service
    image: postgres
    networks:
      - credentials_network
    ports:
      - 5432:5432
    restart: on-failure
    environment:
      - POSTGRES_USER=alesander
      - POSTGRES_PASSWORD=CodexChallenge
      - POSTGRES_DB=codex-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "alesanderlg@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "CodexChallenge"
    ports:
      - "16543:80"
    depends_on:
      - postgresql-service
    networks:
      - credentials_network

networks:
  credentials_network:
    driver: bridge
