# Generated by Django 3.1.4 on 2020-12-21 12:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=128, verbose_name='Manufacturer name')),
                ('model', models.CharField(max_length=128, verbose_name='Model')),
                ('year', models.CharField(max_length=4, verbose_name='yer of amnufacturing')),
            ],
        ),
    ]
